MIN_BOAT_LENGTH = 2  # destroyer
MAX_BOAT_LENGTH = 5  # battleship

MAX_GRID_SIZE = 100
MIN_GRID_SIZE = 8

MAX_BOAT_PLACEMENTS_ATTEMPTS = 100

HORIZONTAL = 0
VERTICAL = 1

HORIZONTAL_STR = "H"
VERTICAL_STR = "V"

DIFFICULTY_ADJUSTMENT_LOW = 1.2
DIFFICULTY_ADJUSTMENT_HIGH = 1.8

DIFFICULTY_LEVEL_LOW = "LOW"
DIFFICULTY_LEVEL_HIGH = "HIGH"

GRID_DIVISOR = 5
