MIN_BOAT_LENGTH = 2
MAX_BOAT_LENGTH = 4  # 5

MAX_GRID_SIZE = 100
MIN_GRID_SIZE = 5

HORIZONTAL = 0
VERTICAL = 1

HORIZONTAL_STR = "H"
VERTICAL_STR = "V"

MAX_BOAT_PLACEMENTS_ATTEMPTS = 100

DIFFICULTY_ADJUSTMENT_LOW = 1.2
DIFFICULTY_ADJUSTMENT_HIGH = 1.8

DIFFICULTY_LEVEL_LOW = "LOW"
DIFFICULTY_LEVEL_HIGH = "HIGH"

GRID_DIVISOR = 5
